In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Data Cleaning 12.08.csv")

In [3]:
df.head()

,name,planet_status,mass,mass_error_min,mass_error_max,mass_sini,mass_sini_error_min,mass_sini_error_max,radius,radius_error_min
0,109 Psc b,Confirmed,5.743,0.289,1.011,6.3830,0.078,0.078,1.152,NaN
1,112 Psc b,Confirmed,NaN,0.005,0.004,0.0330,0.005,0.004,NaN,NaN
2,112 Psc c,Confirmed,9.866,1.781,3.190,NaN,NaN,NaN,NaN,NaN
3,11 UMi b,Confirmed,NaN,1.100,1.100,11.0873,1.100,1.100,NaN,NaN
4,14 And Ab,Confirmed,NaN,0.230,0.230,4.6840,0.230,0.230,NaN,NaN

In [4]:
df.tail()

,name,planet_status,mass,mass_error_min,mass_error_max,mass_sini,mass_sini_error_min,mass_sini_error_max,radius,radius_error_min
5981,YBP 401 b,Confirmed,NaN,0.05000,0.05000,0.46000,0.05000,0.05000,NaN,NaN
5982,YSES 2 b,Confirmed,6.3,0.90000,1.60000,NaN,NaN,NaN,NaN,NaN
5983,YZ Cet b,Confirmed,NaN,0.00028,0.00028,0.00220,0.00028,0.00028,NaN,NaN
5984,YZ Cet c,Confirmed,NaN,0.00035,0.00035,0.00359,0.00035,0.00035,NaN,NaN
5985,YZ Cet d,Confirmed,NaN,0.00038,0.00038,0.00343,0.00038,0.00038,NaN,NaN

In [5]:
df.shape

(5986, 10)

In [6]:
df.columns

Index(['name', 'planet_status', 'mass', 'mass_error_min', 'mass_error_max',
       'mass_sini', 'mass_sini_error_min', 'mass_sini_error_max', 'radius',
       'radius_error_min'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5986 entries, 0 to 5985
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   name                 5986 non-null   object
 1   planet_status        5986 non-null   object
 2   mass                 2079 non-null   float64
 3   mass_error_min       2817 non-null   float64
 4   mass_error_max       2817 non-null   float64
 5   mass_sini            1202 non-null   float64
 6   mass_sini_error_min  1039 non-null   float64
 7   mass_sini_error_max  1039 non-null   float64
 8   radius               4568 non-null   float64
 9   radius_error_min     4093 non-null   float64
dtypes: float64(8), object(2)
memory usage: 467.8+ KB

In [8]:
df.describe()

,mass,mass_error_min,mass_error_max,mass_sini,mass_sini_error_min,mass_sini_error_max,radius,radius_error_min
count,2079.000000,2817.000000,2817.0000,1202.000000,1039.000000,1039.000000,4568.000000,4093.000000
mean,1.492538,0.324366,inf,1.983529,0.214687,0.240453,0.401515,0.048986
std,2.602286,1.351929,NaN,3.199717,0.636474,0.945468,0.430601,0.754220
min,0.000190,0.000000,-17.8000,0.000470,0.000000,0.000000,0.025430,0.000000
25%,0.029655,0.006290,0.0057,0.045000,0.005940,0.005300,0.145000,0.010000
50%,0.370000,0.041000,0.0400,0.731500,0.049300,0.050000,0.219000,0.020000
75%,1.466500,0.170000,0.1700,2.400000,0.170000,0.170000,0.384000,0.042000
max,12.934000,53.500000,inf,50.000000,13.000000,20.900000,6.900000,48.000000

In [17]:
df.isnull().sum()

name                      0
planet_status             0
mass                   3907
mass_error_min         3169
mass_error_max         3169
mass_sini              4784
mass_sini_error_min    4947
mass_sini_error_max    4947
radius                 1418
radius_error_min       1893
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.columns = df.columns.str.strip()

In [14]:
df['name'] = df['name'].str.strip()

In [15]:
df['planet_status'] = df['planet_status'].str.strip()

In [16]:
df['planet_status'].value_counts()

planet_status
Confirmed    5986
Name: count, dtype: int64

In [18]:
df.dtypes

name                    object
planet_status           object
mass                   float64
mass_error_min         float64
mass_error_max         float64
mass_sini              float64
mass_sini_error_min    float64
mass_sini_error_max    float64
radius                 float64
radius_error_min       float64
dtype: object

In [19]:
df['mass'] = pd.to_numeric(df['mass'], errors='coerce')

In [20]:
df['radius'] = pd.to_numeric(df['radius'], errors='coerce')

In [21]:
numeric_columns = [
    'mass_error_min',
    'mass_error_max',
    'mass_sini',
    'mass_sini_error_min',
    'mass_sini_error_max',
    'radius_error_min'
]

for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [22]:
df.dropna(subset=['name', 'planet_status'], inplace=True)

In [23]:
df.isnull().sum()

name                      0
planet_status             0
mass                   3907
mass_error_min         3169
mass_error_max         3169
mass_sini              4784
mass_sini_error_min    4947
mass_sini_error_max    4947
radius                 1418
radius_error_min       1893
dtype: int64

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5986 entries, 0 to 5985
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   name                 5986 non-null   object
 1   planet_status        5986 non-null   object
 2   mass                 2079 non-null   float64
 3   mass_error_min       2817 non-null   float64
 4   mass_error_max       2817 non-null   float64
 5   mass_sini            1202 non-null   float64
 6   mass_sini_error_min  1039 non-null   float64
 7   mass_sini_error_max  1039 non-null   float64
 8   radius               4568 non-null   float64
 9   radius_error_min     4093 non-null   float64
dtypes: float64(8), object(2)
memory usage: 467.8+ KB

In [25]:
df.head()

,name,planet_status,mass,mass_error_min,mass_error_max,mass_sini,mass_sini_error_min,mass_sini_error_max,radius,radius_error_min
0,109 Psc b,Confirmed,5.743,0.289,1.011,6.3830,0.078,0.078,1.152,NaN
1,112 Psc b,Confirmed,NaN,0.005,0.004,0.0330,0.005,0.004,NaN,NaN
2,112 Psc c,Confirmed,9.866,1.781,3.190,NaN,NaN,NaN,NaN,NaN
3,11 UMi b,Confirmed,NaN,1.100,1.100,11.0873,1.100,1.100,NaN,NaN
4,14 And Ab,Confirmed,NaN,0.230,0.230,4.6840,0.230,0.230,NaN,NaN

In [26]:
df.shape

(5986, 10)

In [28]:
df.to_excel("cleaned_planets_data.xlsx", index=False)